---
kind: Secret
apiVersion: v1
metadata:
    name: jenkins-maven-settings
data:
    settings-security.xml: "PHNldHRpbmdzU2VjdXJpdHkvPg=="
    settings.xml: "{{ .Values.settingsXml | replace "#secrets.gitUsername#" .Values.secrets.gitUsername | replace "#secrets.gitPassword#" .Values.secrets.gitPassword | b64enc }}"
