---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: tekton-bot
rules:
    # needs access to GIT, Artifactory etc. credentials
    - apiGroups:
          - ""
      resources:
          - configmaps
          - secrets
          - services
      verbs:
          - get
          - list
          - watch

    # requires access to Jenkins X configuration specified for this namespace
    - apiGroups:
          - "jenkins.io"
      resources:
          - environments
      verbs:
          - get
          - list
          - watch

    - apiGroups:
        - "jenkins.io"
      resources:
          - pipelineactivities
      verbs:
          - get
          - list
          - create
          - update
