---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: tekton-bot
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tekton-bot
subjects:
    - kind: ServiceAccount
      name: tekton-bot
