---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: tekton-bot
rules:
{{ if .Values.isNamespaceAdmin -}}
    - apiGroups:
          - '*'
      resources:
          - '*'
      verbs:
          - '*'
    - nonResourceURLs:
          - '*'
      verbs:
          - '*'
{{- else }}
    # needs access to GIT, Artifactory etc. credentials
    - apiGroups:
          - ""
      resources:
          - configmaps
          - secrets
          - services
      verbs:
          - get
          - list

    # jx gitops variables
    - apiGroups:
        - "networking.k8s.io"
      resources:
          - ingresses
      verbs:
          - get
          - list

    # requires access to Jenkins X configuration specified for this namespace
    - apiGroups:
          - "jenkins.io"
      resources:
          - environments
      verbs:
          - get
          - list
          - watch

    - apiGroups:
        - "jenkins.io"
      resources:
          - pipelineactivities
      verbs:
          - get
          - list
          - create
          - update
{{ end }}
