---
apiVersion: v1
kind: Secret
metadata:
    name: tekton-container-registry-auth
data:
    .dockerconfigjson: "{{ .Values.secrets.registryDockerConfigJson | b64enc }}"
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
    name: tekton-git
data:
    username: "{{ .Values.secrets.gitUsername | b64enc }}"
    password: "{{ .Values.secrets.gitPassword | b64enc }}"
type: kubernetes.io/basic-auth
