
# namespace admin can perform deployments in SAME NAMESPACE
# while if .isNamespaceAdmin is set to false, then only necessary permissions for pipeline completion (without CD part) are granted
isNamespaceAdmin: false

secrets:
    registryDockerConfigJson: |
        {
            "auths":{
                "ghcr.io": {
                    "auth": "tralalalala"
                }
            }
        }
    gitUsername: "user"
    gitPassword: "password"
    gitProviderUrl: https://github.com

serviceAccounts:
    - serviceAccountName: tekton-bot
      imagePullSecrets:
          - name: tekton-container-registry-auth
      secrets:
          - name: tekton-git
          - name: tekton-container-registry-auth

environment:
    name: dev
    installRepo:
        branch: master
        url: ...
    settings:
        appsRepository: https://jenkins-x-charts.github.io/repo
        defaultScheduler:
            apiVersion: jenkins.io/v1
            kind: Scheduler
            name: jx-meta-pipeline
        dockerRegistryOrg: ""
        envOrganisation: todo
        gitServer: https://github.com
        kubeProvider: kubernetes
        pipelineUserEmail: jenkins-x@googlegroups.com
        pipelineUsername: ...
        prowConfig: Scheduler

settingsXml: |
    <settings>
        <localRepository>/home/jenkins/.mvnrepository</localRepository>
        <!--This sends everything else to /public -->
          <mirrors>
              <mirror>
                  <id>bucketrepo</id>
                  <name>bucketrepo mirror</name>
                  <mirrorOf>*</mirrorOf>
                  <url>http://bucketrepo/bucketrepo/</url>
              </mirror>
            </mirrors>

        <!-- lets disable the download progress indicator that fills up logs -->
        <interactiveMode>false</interactiveMode>

        <servers>
            <server>
                <id>local-nexus</id>
                <username>admin</username>
                <password></password>
            </server>
            <server>
                <id>nexus</id>
                <username>admin</username>
                <password></password>
            </server>
            <server>
                <id>chartmuseum</id>
                <username></username>
                <password></password>
            </server>
            <server>
                <id>bucketrepo</id>
                <username></username>
                <password></password>
            </server>
            <server>
                <id>oss-sonatype-staging</id>
                <username></username>
                <password></password>
            </server>
            <server>
                <id>docker.io</id>
                <username></username>
                <password></password>
            </server>
            <server>
              <id>github</id>
              <username>#secrets.gitUsername#</username>
              <password>#secrets.gitPassword#</password>
            </server>
        </servers>

        <profiles>
            <profile>
                <id>nexus</id>
                <properties>
                  <altDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/</altDeploymentRepository>
                  <altReleaseDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/</altReleaseDeploymentRepository>
                  <altSnapshotDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/snapshots/</altSnapshotDeploymentRepository>
                </properties>

                <repositories>
                    <repository>
                        <id>central</id>
                        <url>http://central</url>
                        <releases><enabled>true</enabled></releases>
                        <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                </repositories>
                <pluginRepositories>
                    <pluginRepository>
                        <id>central</id>
                        <url>http://central</url>
                        <releases><enabled>true</enabled></releases>
                        <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                </pluginRepositories>
            </profile>
            <profile>
                <id>repo.jenkins-ci.org</id>
                <properties>
                    <altDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/releases/</altDeploymentRepository>
                    <altReleaseDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/releases/</altReleaseDeploymentRepository>
                    <altSnapshotDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/snapshots/</altSnapshotDeploymentRepository>
                </properties>

            </profile>
            <profile>
                <id>maven.jenkins-ci.org</id>
                <properties>
                    <altDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/releases/</altDeploymentRepository>
                    <altReleaseDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/releases/</altReleaseDeploymentRepository>
                    <altSnapshotDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/snapshots/</altSnapshotDeploymentRepository>
                </properties>

            </profile>
            <profile>
                <id>release</id>
                <properties>
                    <gpg.executable>gpg</gpg.executable>
                    <!-- TODO use: .Parameters.gpg.passphrase when it is always populated -->
                    <gpg.passphrase></gpg.passphrase>
                </properties>
            </profile>
        </profiles>

        <activeProfiles>
            <activeProfile>nexus</activeProfile>
        </activeProfiles>
    </settings>
